siteNuvemCriativa90/Controllers/EmpresasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using siteNuvemCriativa90.Data;
using siteNuvemCriativa90.Models;

namespace siteNuvemCriativa90.Controllers
{
    public class EmpresasController : Controller
    {
        private readonly siteNuvemCriativa90DBContext _context;

        public EmpresasController(siteNuvemCriativa90DBContext context)
        {
            _context = context;
        }
        // GET: Empresas
        public async Task<IActionResult> Index()
        {
            var siteNuvemCriativa90DBContext = _context.Empresas.Include(e => e.Endereco).Include(e => e.GrupoUsuario).Where(u => u.Apagado == "N");
            return View(await siteNuvemCriativa90DBContext.ToListAsync());
        }

        // GET: Empresas/Details/5
        public async Task<IActionResult> Detalhes(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empresa = await _context.Empresas
                .Include(e => e.Endereco)
                .Include(e => e.GrupoUsuario)
                .FirstOrDefaultAsync(m => m.IDEmpresa == id);
            if (empresa == null)
            {
                return NotFound();
            }

            return View(empresa);
        }
        public IActionResult Cadastrar()
        {
            ViewData["IDEndereco"] = new SelectList(_context.Enderecos, "IDEndereco", "Logradouro");
            ViewData["IDGrupoUsuario"] = new SelectList(_context.GrupoUsuarios, "IDGrupoUsuario", "TipoUsuario");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cadastrar([Bind("IDEmpresa,Login,Senha,CNPJ,RazaoSocial,NomeFantasia,Email,Telefone,Necessidade,Ramo,DataCadastro,Apagado,IDEndereco,IDGrupoUsuario")] Empresa empresa)
        {
            try
            {
                empresa.Apagado = "N";
                empresa.DataCadastro = DateTime.Now;
                _context.Add(empresa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                ViewData["IDEndereco"] = new SelectList(_context.Enderecos, "IDEndereco", "Logradouro", empresa.IDEndereco);
                ViewData["IDGrupoUsuario"] = new SelectList(_context.GrupoUsuarios, "IDGrupoUsuario", "TipoUsuario", empresa.IDGrupoUsuario);
                return View(empresa);
            }

        }




        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empresa = await _context.Empresas.FindAsync(id);
            if (empresa == null)
            {
                return NotFound();
            }
            ViewData["IDEndereco"] = new SelectList(_context.Enderecos, "IDEndereco", "Logradouro", empresa.IDEndereco);
            ViewData["IDGrupoUsuario"] = new SelectList(_context.GrupoUsuarios, "IDGrupoUsuario", "TipoUsuario", empresa.IDGrupoUsuario);
            return View(empresa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, [Bind("IDEmpresa,Login,Senha,CNPJ,RazaoSocial,NomeFantasia,Email,Telefone, Necessidade,Ramo,DataCadastro,Apagado,IDEndereco,IDGrupoUsuario")] Empresa empresa)
        {
            if (id != empresa.IDEmpresa)
            {
                return NotFound();
            }
            try
            {
                empresa.Apagado = "N";
                _context.Update(empresa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EmpresaExists(empresa.IDEmpresa))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
        }

        public async Task<IActionResult> Excluir(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empresa = await _context.Empresas
               .Include(e => e.Endereco)
               .Include(e => e.GrupoUsuario)
               .FirstOrDefaultAsync(m => m.IDEmpresa == id);
            if (empresa == null)
            {
                return NotFound();
            }

            return View(empresa);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmacaoExcluir(int id, [Bind("IDEmpresa,Login,Senha,CNPJ,RazaoSocial,NomeFantasia,Email,Telefone,Necessidade,Ramo,DataCadastro,Apagado,IDEndereco,IDGrupoUsuario")] Empresa empresa)
        {
            if (id != empresa.IDEmpresa)
            {
                return NotFound();
            }
            try
            {
                empresa.Apagado = "S";
                _context.Update(empresa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EmpresaExists(empresa.IDEmpresa))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
        }

        private bool EmpresaExists(int id)
        {
            return _context.Empresas.Any(e => e.IDEmpresa == id);
        }
    }
}

siteNuvemCriativa90/Controllers/EnderecosController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using siteNuvemCriativa90.Models;
using System.IO;
using siteNuvemCriativa90.Data;
using Rotativa.AspNetCore;

namespace siteNuvemCriativa90.Controllers
{
    public class EnderecosController : Controller
    {
           private readonly siteNuvemCriativa90DBContext _context;

        public EnderecosController(siteNuvemCriativa90DBContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Relatorio_de_Endereco()
        {
            var siteNuvemCriativa90DBContext = _context.Enderecos.ToList().Where(grupo => grupo.Apagado == "N");
            return new ViewAsPdf(siteNuvemCriativa90DBContext.ToList());
        }
        public async Task<IActionResult> Index()
        {
            var siteNuvemCriativa90DBContext = _context.Enderecos.ToList().Where(grupo => grupo.Apagado == "N");
            return View(siteNuvemCriativa90DBContext.ToList());
        }
        public async Task<IActionResult> Detalhes(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endereco = await _context.Enderecos
                .FirstOrDefaultAsync(m => m.IDEndereco == id);
            if (endereco == null)
            {
                return NotFound();
            }

            return View(endereco);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cadastrar([Bind("IDEndereco,Cidade,UF,Logradouro,Numero,Apagado")] Endereco endereco)
        {
            try
            {
                endereco.Apagado = "N";
                _context.Add(endereco);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));

            }
            catch (Exception)
            {

                return RedirectToAction(nameof(Index));
            }

        }

        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endereco = await _context.Enderecos.FindAsync(id);
            if (endereco == null)
            {
                return NotFound();
            }
            return View(endereco);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int id, [Bind("IDEndereco,Cidade,UF,Logradouro,Numero,Apagado")] Endereco endereco)
        {
            if (id != endereco.IDEndereco)
            {
                return NotFound();
            }

            try
            {
                endereco.Apagado = "N";
                 _context.Update(endereco);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EnderecoExists(endereco.IDEndereco))
                {
                    return NotFound();
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
        }

        public async Task<IActionResult> Excluir(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endereco = await _context.Enderecos
                .FirstOrDefaultAsync(m => m.IDEndereco == id);
            if (endereco == null)
            {
                return NotFound();
            }

            return View(endereco);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmacaoExcluir(int id, [Bind("IDEndereco,Cidade,UF,Logradouro,Numero,Apagado")] Endereco endereco)
        {
            if (id != endereco.IDEndereco)
            {
                return NotFound();
            }
            try
            {
                endereco.Apagado = "S";
                _context.Update(endereco);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EnderecoExists(endereco.IDEndereco))
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
        }
        private bool EnderecoExists(int id)
        {
            return _context.Enderecos.Any(e => e.IDEndereco == id);
        }

    }
}


siteNuvemCriativa90/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Nuvem Criativa 90 &mdash; @ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="~/Assets/NuvemLogo.png" style="margin-right: 2em;height: 80px;">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="drop nav-item nav-link dropdown-toggle mr-md-2" href="#" id="bd-versions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Cadastros
                            </a>
                            <div class="drop dropdown-menu dropdown-menu-right" aria-labelledby="bd-versions">
                                <a class="drop dropdown-item" asp-area="Identity" asp-page="/Account/Register">Usuários</a>
                                <a class="drop dropdown-item" asp-controller="Empresas" asp-action="Index">Empresas</a>
                                <a class="drop dropdown-item" asp-controller="Enderecos" asp-action="Index">Endereços</a>
                                <div class="dropdown-divider"></div>
                                <a class="drop dropdown-item" asp-controller="Empresas" asp-action="Index">Portifolios</a>
                            </div>
                        </li>
                    </ul>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Regular link</a>
                        <a class="dropdown-item active" href="#">Active link</a>
                        <a class="dropdown-item" href="#">Another link</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;
                <script>document.write(new Date().getFullYear());</script> | Todos direitos reservados - Nuvem Criativa 90
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>